### ISSUE TITLE
Support for array of object validation?

### ISSUE THREAD

**Issue by kevinludwig** [funcool/struct#11]
I'm not sure if this is supported, but how do I validate the type of objects nested inside an array, e.g. `{:addresses [{:street "blah" :city "wherever" :state "NY" :zip 12345} {:street "another street" :city "another city" :state "MA" :zip 34234}]}`?

I've figured out that I can do a schema like `{:addresses [st/vector]}` but that's hardly useful since it allows anything in the addresses vector.

I see there is some basic support for checking every method of an array, e.g. `st/every` although I was unable to get that working even for a trivial case like this `(st/validate {:xs ["a" "b"]} {:xs [st/every string?]})`. That throws:

`ClassCastException clojure.core$string_QMARK___4365 cannot be cast to clojure.lang.Associative  clojure.lang.RT.assoc (RT.java:792)`

And there is no example in the documentation that shows how to use `st/every` so its not clear to me if I'm doing it wrong or if it just doesn't work.

**Comment by niwinz** [comment]
You should use the st/vector together with st/every.
