### ISSUE TITLE
Validating nested data structures

### ISSUE THREAD

**Issue by emiln** [funcool/struct#3]
Hi, funcool, and thanks for this refreshingly simple validation library. I've been looking for something like this for a while. However, I have a few questions I hope you can help answer.

How should I use `struct` to validate nested data structures? Let's say I have the following data:

``` clojure
(def user
  {:age 28
   :name {:first "Emil"
          :last "Nauerby"}})
```

I would like to be able to express a nested validation like the following:

``` clojure
(st/validate
  user
  {:age [st/required st/number]
   :name {:first [st/required st/number]
          :last [st/required st/number]}})
```

but this doesn't actually do the validation (as it's probably now it's intended to be done).

So how would I go about validating nested data structures?

**Comment by niwinz** [comment]
At this moment no neested data structures validation is supported. But the architecture is done in the way that adding that feature will be very easy.

I hope that for the next version I will add support for validation of neested data structures.

The syntax will be:

``` clojure
{:age [st/required st/number]
 [:name :first] [st/required st/number]
 [:name :last] [st/required st/number]}
```

or

``` clojure
[[:age st/required st/number]
 [[:name :first] st/required st/number]
 [[:name :last] st/required st/number]]
```

**Comment by emiln** [comment]
Thank you for the quick response. It's great to hear it's on the roadmap. Is there any way for me to keep myself updated with how the project is progressing? Do you use e.g. milestones on GitHub?

**Comment by niwinz** [comment]
I'm just use issues, and in some time "releases". Keep watching the library and surely you will be notified when the issue is closed or new release is issued.

**Comment by niwinz** [comment]
@emiln released `0.2.0-SNAPSHOT` with this change and some others already documented in CHANGES.md file (some breaking changes and performance improvements).

**Comment by ayato-p** [comment]
Hi.

I found a strange behavior, maybe related this issue.

```clj
(def nested-form 
  [[:age s/required s/number]
   [[:name :first] s/required s/string]
   [[:name :last] s/required s/string]])

(let [data {:age 10
                 :name {:first "Taro" :last ""}}]
  (s/validate data nested-form))
```

This is fine. However, if I use `min-count` or any other validators with vector literal, then struct just does not work. Like following.

```clj
(def nested-form 
  [[:age s/required s/number]
   [[:name :first] s/required s/string]
   [[:name :last] s/required s/string [s/min-count 3]])

(let [data {:age 10
                 :name {:first "Taro" :last "N"}}]
  (s/validate data nested-form)) ;; struct dont care about min-count validator
```

So, is this a bug?

And I just curious how I validate a map, which has a vector keys.

```clj
;; How I validate this map?
{[:name :first] "Taro"
 [:name :last] "Nagasawa"}
```

**Comment by ayato-p** [comment]
@niwinz ping
