### ISSUE TITLE
templatize customized error messages?

### ISSUE THREAD

**Issue by mattly** [funcool/struct#6]
Let's say you had a parameterized validator like `in-range`:

```
(st/validate {:a 10} {:a [[st/in-range 1 9]]})
[{:a ("not in range")} {}]
```

and you wanted that message to say "not between 1 to 9". How would you go about this? Making a custom validator? With error codes?

Thanks for the library, it seems like it'll be a nice alternative to bouncer.

**Comment by niwinz** [comment]
At this moment teplating is not suported (mainly because I didn't find it useful on the end) but I think it can be easily implemented.

**Comment by niwinz** [comment]
Let's try the `1.1.0-SNAPSHOT`. I now should support proper interpolation. There a little example:

``` clojure
(s/validate {:a 10} {:a [[s/in-range 1 9 :message "should between $0 and $1"]]})
;; => [{:a "should between 1 and 9"} {}]
```

**Comment by mattly** [comment]
Works wonderfully, thanks.
