### ISSUE TITLE
Is it possible to attach validator not to particular field?

### ISSUE THREAD

**Issue by kirillsalykin** [funcool/struct#8]
Sometimes there is no invalid field, the whole record is wrong. For instance, validating email/password.

Maybe we can use `:base` field for such scenarios (and treat it specially)? (Similar to Ruby on Rails).

Thanks!

**Comment by niwinz** [comment]
I didn't see this issue until now, my apoloigies.

And, no, there are no way to setup a "global" validator at this moment.
